### ISSUE TITLE
Visit list in wb has channel units=0 for all 2015, 2016, 2017 visits

### ISSUE THREAD

**Issue by volkcj** [NorthArrowResearch/champ-workbench#34]
https://dl.dropboxusercontent.com/u/22543727/Snapshots/2017-07-19_163952.png

**Comment by philipbaileynar** [comment]
This appears to be something to do with permissions. Weird that it would be affecting a single year... I'll check in with Sitka.

**Comment by philipbaileynar** [comment]
Or it might be timing out

**Comment by philipbaileynar** [comment]
This was resolved for Workbench version [7.0.20 on 27 Sep 2017](http://workbench.northarrowresearch.com/release_notes.html). It was actually related to tier metrics having a name of "0" when a visit doesn't possess a particular channel unit type (e.g. small side channel). This value of "0" then blowing up the metric download because it couldn't be found in the lookup list dictionary of tier names.
